### ISSUE TITLE
Missing a cool gif

### ISSUE THREAD

**Issue by shubham-padia** [himanshub16/dexter#1]
Jeet ke aana hihi  :stuck_out_tongue_winking_eye: 
![image](https://media.giphy.com/media/H9r3nM25USSis/giphy.gif)

**Comment by thelittlewonder** [comment]
HiHi so gya 😂

**Comment by shubham-padia** [comment]
:joy:

**Comment by littlewonder** [comment]
Readme padh ke bta, idea kaisa hai 😜

**Comment by shubham-padia** [comment]
Kaafi sahi hai `_/\__/\_`
Glad you kept Hindi #abBajrangDalBhiKaregaCode.
