### ISSUE TITLE
WebSpeechAPI failing

### ISSUE THREAD

**Issue by tmess567** [himanshub16/dexter#6]
Google Web Speech API is failing with the following error on console: 
recognition says: wtf not-allowed

I’m guessing this might be because of the commented code in https://github.com/himanshub16/dexter/blob/master/js/mic.js

**Comment by himanshub16** [comment]
Hi @tmess567 ,
Are you directly opening the HTML page in browser, or using a local server to run it.
AFAIK, Chrome's Speech API let me use it on `localhost` but not on `file:///pathtofile/index.html`.
